// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: matchmaker/v1/matchmaker.proto

package matchmaker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentGameRequest) Reset() {
	*x = GetCurrentGameRequest{}
	mi := &file_matchmaker_v1_matchmaker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentGameRequest) ProtoMessage() {}

func (x *GetCurrentGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_v1_matchmaker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentGameRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentGameRequest) Descriptor() ([]byte, []int) {
	return file_matchmaker_v1_matchmaker_proto_rawDescGZIP(), []int{0}
}

type GetCurrentGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentGameResponse) Reset() {
	*x = GetCurrentGameResponse{}
	mi := &file_matchmaker_v1_matchmaker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentGameResponse) ProtoMessage() {}

func (x *GetCurrentGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_v1_matchmaker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentGameResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentGameResponse) Descriptor() ([]byte, []int) {
	return file_matchmaker_v1_matchmaker_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentGameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_matchmaker_v1_matchmaker_proto protoreflect.FileDescriptor

const file_matchmaker_v1_matchmaker_proto_rawDesc = "" +
	"\n" +
	"\x1ematchmaker/v1/matchmaker.proto\"\x17\n" +
	"\x15GetCurrentGameRequest\",\n" +
	"\x16GetCurrentGameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2O\n" +
	"\n" +
	"Matchmaker\x12A\n" +
	"\x0eGetCurrentGame\x12\x16.GetCurrentGameRequest\x1a\x17.GetCurrentGameResponseB2Z0github.com/tobyrushton/globalfront/pb/matchmakerb\x06proto3"

var (
	file_matchmaker_v1_matchmaker_proto_rawDescOnce sync.Once
	file_matchmaker_v1_matchmaker_proto_rawDescData []byte
)

func file_matchmaker_v1_matchmaker_proto_rawDescGZIP() []byte {
	file_matchmaker_v1_matchmaker_proto_rawDescOnce.Do(func() {
		file_matchmaker_v1_matchmaker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matchmaker_v1_matchmaker_proto_rawDesc), len(file_matchmaker_v1_matchmaker_proto_rawDesc)))
	})
	return file_matchmaker_v1_matchmaker_proto_rawDescData
}

var file_matchmaker_v1_matchmaker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_matchmaker_v1_matchmaker_proto_goTypes = []any{
	(*GetCurrentGameRequest)(nil),  // 0: GetCurrentGameRequest
	(*GetCurrentGameResponse)(nil), // 1: GetCurrentGameResponse
}
var file_matchmaker_v1_matchmaker_proto_depIdxs = []int32{
	0, // 0: Matchmaker.GetCurrentGame:input_type -> GetCurrentGameRequest
	1, // 1: Matchmaker.GetCurrentGame:output_type -> GetCurrentGameResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_matchmaker_v1_matchmaker_proto_init() }
func file_matchmaker_v1_matchmaker_proto_init() {
	if File_matchmaker_v1_matchmaker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matchmaker_v1_matchmaker_proto_rawDesc), len(file_matchmaker_v1_matchmaker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matchmaker_v1_matchmaker_proto_goTypes,
		DependencyIndexes: file_matchmaker_v1_matchmaker_proto_depIdxs,
		MessageInfos:      file_matchmaker_v1_matchmaker_proto_msgTypes,
	}.Build()
	File_matchmaker_v1_matchmaker_proto = out.File
	file_matchmaker_v1_matchmaker_proto_goTypes = nil
	file_matchmaker_v1_matchmaker_proto_depIdxs = nil
}
