// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: matchmaker/v1/matchmaker.proto

package v1

import (
	v1 "github.com/tobyrushton/globalfront/pb/game/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentGameRequest) Reset() {
	*x = GetCurrentGameRequest{}
	mi := &file_matchmaker_v1_matchmaker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentGameRequest) ProtoMessage() {}

func (x *GetCurrentGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_v1_matchmaker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentGameRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentGameRequest) Descriptor() ([]byte, []int) {
	return file_matchmaker_v1_matchmaker_proto_rawDescGZIP(), []int{0}
}

type GetCurrentGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *v1.Game               `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentGameResponse) Reset() {
	*x = GetCurrentGameResponse{}
	mi := &file_matchmaker_v1_matchmaker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentGameResponse) ProtoMessage() {}

func (x *GetCurrentGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaker_v1_matchmaker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentGameResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentGameResponse) Descriptor() ([]byte, []int) {
	return file_matchmaker_v1_matchmaker_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentGameResponse) GetGame() *v1.Game {
	if x != nil {
		return x.Game
	}
	return nil
}

var File_matchmaker_v1_matchmaker_proto protoreflect.FileDescriptor

const file_matchmaker_v1_matchmaker_proto_rawDesc = "" +
	"\n" +
	"\x1ematchmaker/v1/matchmaker.proto\x12\rmatchmaker.v1\x1a\x12game/v1/game.proto\"\x17\n" +
	"\x15GetCurrentGameRequest\";\n" +
	"\x16GetCurrentGameResponse\x12!\n" +
	"\x04game\x18\x01 \x01(\v2\r.game.v1.GameR\x04game2k\n" +
	"\n" +
	"Matchmaker\x12]\n" +
	"\x0eGetCurrentGame\x12$.matchmaker.v1.GetCurrentGameRequest\x1a%.matchmaker.v1.GetCurrentGameResponseB5Z3github.com/tobyrushton/globalfront/pb/matchmaker/v1b\x06proto3"

var (
	file_matchmaker_v1_matchmaker_proto_rawDescOnce sync.Once
	file_matchmaker_v1_matchmaker_proto_rawDescData []byte
)

func file_matchmaker_v1_matchmaker_proto_rawDescGZIP() []byte {
	file_matchmaker_v1_matchmaker_proto_rawDescOnce.Do(func() {
		file_matchmaker_v1_matchmaker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matchmaker_v1_matchmaker_proto_rawDesc), len(file_matchmaker_v1_matchmaker_proto_rawDesc)))
	})
	return file_matchmaker_v1_matchmaker_proto_rawDescData
}

var file_matchmaker_v1_matchmaker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_matchmaker_v1_matchmaker_proto_goTypes = []any{
	(*GetCurrentGameRequest)(nil),  // 0: matchmaker.v1.GetCurrentGameRequest
	(*GetCurrentGameResponse)(nil), // 1: matchmaker.v1.GetCurrentGameResponse
	(*v1.Game)(nil),                // 2: game.v1.Game
}
var file_matchmaker_v1_matchmaker_proto_depIdxs = []int32{
	2, // 0: matchmaker.v1.GetCurrentGameResponse.game:type_name -> game.v1.Game
	0, // 1: matchmaker.v1.Matchmaker.GetCurrentGame:input_type -> matchmaker.v1.GetCurrentGameRequest
	1, // 2: matchmaker.v1.Matchmaker.GetCurrentGame:output_type -> matchmaker.v1.GetCurrentGameResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_matchmaker_v1_matchmaker_proto_init() }
func file_matchmaker_v1_matchmaker_proto_init() {
	if File_matchmaker_v1_matchmaker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matchmaker_v1_matchmaker_proto_rawDesc), len(file_matchmaker_v1_matchmaker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matchmaker_v1_matchmaker_proto_goTypes,
		DependencyIndexes: file_matchmaker_v1_matchmaker_proto_depIdxs,
		MessageInfos:      file_matchmaker_v1_matchmaker_proto_msgTypes,
	}.Build()
	File_matchmaker_v1_matchmaker_proto = out.File
	file_matchmaker_v1_matchmaker_proto_goTypes = nil
	file_matchmaker_v1_matchmaker_proto_depIdxs = nil
}
