// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: messages/v1/messages.proto

package v1

import (
	v1 "github.com/tobyrushton/globalfront/pb/game/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED   MessageType = 0
	MessageType_MESSAGE_START_COUNTDOWN    MessageType = 1
	MessageType_MESSAGE_GAME_START         MessageType = 2
	MessageType_MESSAGE_JOIN_GAME          MessageType = 3
	MessageType_MESSAGE_JOIN_GAME_RESPONSE MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_START_COUNTDOWN",
		2: "MESSAGE_GAME_START",
		3: "MESSAGE_JOIN_GAME",
		4: "MESSAGE_JOIN_GAME_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":   0,
		"MESSAGE_START_COUNTDOWN":    1,
		"MESSAGE_GAME_START":         2,
		"MESSAGE_JOIN_GAME":          3,
		"MESSAGE_JOIN_GAME_RESPONSE": 4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_v1_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_messages_v1_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_messages_v1_messages_proto_rawDescGZIP(), []int{0}
}

type WebsocketMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=messages.v1.MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WebsocketMessage_StartCountdown
	//	*WebsocketMessage_GameStart
	//	*WebsocketMessage_JoinGame
	//	*WebsocketMessage_JoinGameResponse
	Payload       isWebsocketMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketMessage) Reset() {
	*x = WebsocketMessage{}
	mi := &file_messages_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketMessage) ProtoMessage() {}

func (x *WebsocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketMessage.ProtoReflect.Descriptor instead.
func (*WebsocketMessage) Descriptor() ([]byte, []int) {
	return file_messages_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *WebsocketMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *WebsocketMessage) GetPayload() isWebsocketMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebsocketMessage) GetStartCountdown() *StartCountdown {
	if x != nil {
		if x, ok := x.Payload.(*WebsocketMessage_StartCountdown); ok {
			return x.StartCountdown
		}
	}
	return nil
}

func (x *WebsocketMessage) GetGameStart() *GameStart {
	if x != nil {
		if x, ok := x.Payload.(*WebsocketMessage_GameStart); ok {
			return x.GameStart
		}
	}
	return nil
}

func (x *WebsocketMessage) GetJoinGame() *JoinGame {
	if x != nil {
		if x, ok := x.Payload.(*WebsocketMessage_JoinGame); ok {
			return x.JoinGame
		}
	}
	return nil
}

func (x *WebsocketMessage) GetJoinGameResponse() *JoinGameResponse {
	if x != nil {
		if x, ok := x.Payload.(*WebsocketMessage_JoinGameResponse); ok {
			return x.JoinGameResponse
		}
	}
	return nil
}

type isWebsocketMessage_Payload interface {
	isWebsocketMessage_Payload()
}

type WebsocketMessage_StartCountdown struct {
	StartCountdown *StartCountdown `protobuf:"bytes,2,opt,name=start_countdown,json=startCountdown,proto3,oneof"`
}

type WebsocketMessage_GameStart struct {
	GameStart *GameStart `protobuf:"bytes,3,opt,name=game_start,json=gameStart,proto3,oneof"`
}

type WebsocketMessage_JoinGame struct {
	JoinGame *JoinGame `protobuf:"bytes,4,opt,name=join_game,json=joinGame,proto3,oneof"`
}

type WebsocketMessage_JoinGameResponse struct {
	JoinGameResponse *JoinGameResponse `protobuf:"bytes,5,opt,name=join_game_response,json=joinGameResponse,proto3,oneof"`
}

func (*WebsocketMessage_StartCountdown) isWebsocketMessage_Payload() {}

func (*WebsocketMessage_GameStart) isWebsocketMessage_Payload() {}

func (*WebsocketMessage_JoinGame) isWebsocketMessage_Payload() {}

func (*WebsocketMessage_JoinGameResponse) isWebsocketMessage_Payload() {}

type StartCountdown struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CountdownSeconds int32                  `protobuf:"varint,1,opt,name=countdown_seconds,json=countdownSeconds,proto3" json:"countdown_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartCountdown) Reset() {
	*x = StartCountdown{}
	mi := &file_messages_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCountdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCountdown) ProtoMessage() {}

func (x *StartCountdown) ProtoReflect() protoreflect.Message {
	mi := &file_messages_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCountdown.ProtoReflect.Descriptor instead.
func (*StartCountdown) Descriptor() ([]byte, []int) {
	return file_messages_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *StartCountdown) GetCountdownSeconds() int32 {
	if x != nil {
		return x.CountdownSeconds
	}
	return 0
}

type GameStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStart) Reset() {
	*x = GameStart{}
	mi := &file_messages_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStart) ProtoMessage() {}

func (x *GameStart) ProtoReflect() protoreflect.Message {
	mi := &file_messages_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStart.ProtoReflect.Descriptor instead.
func (*GameStart) Descriptor() ([]byte, []int) {
	return file_messages_v1_messages_proto_rawDescGZIP(), []int{2}
}

type JoinGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGame) Reset() {
	*x = JoinGame{}
	mi := &file_messages_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGame) ProtoMessage() {}

func (x *JoinGame) ProtoReflect() protoreflect.Message {
	mi := &file_messages_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGame.ProtoReflect.Descriptor instead.
func (*JoinGame) Descriptor() ([]byte, []int) {
	return file_messages_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *JoinGame) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type JoinGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*v1.Player           `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Board         *v1.Board              `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGameResponse) Reset() {
	*x = JoinGameResponse{}
	mi := &file_messages_v1_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameResponse) ProtoMessage() {}

func (x *JoinGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_v1_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameResponse.ProtoReflect.Descriptor instead.
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return file_messages_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *JoinGameResponse) GetPlayers() []*v1.Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *JoinGameResponse) GetBoard() *v1.Board {
	if x != nil {
		return x.Board
	}
	return nil
}

var File_messages_v1_messages_proto protoreflect.FileDescriptor

const file_messages_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1amessages/v1/messages.proto\x12\vmessages.v1\x1a\x12game/v1/game.proto\"\xd1\x02\n" +
	"\x10WebsocketMessage\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.messages.v1.MessageTypeR\x04type\x12F\n" +
	"\x0fstart_countdown\x18\x02 \x01(\v2\x1b.messages.v1.StartCountdownH\x00R\x0estartCountdown\x127\n" +
	"\n" +
	"game_start\x18\x03 \x01(\v2\x16.messages.v1.GameStartH\x00R\tgameStart\x124\n" +
	"\tjoin_game\x18\x04 \x01(\v2\x15.messages.v1.JoinGameH\x00R\bjoinGame\x12M\n" +
	"\x12join_game_response\x18\x05 \x01(\v2\x1d.messages.v1.JoinGameResponseH\x00R\x10joinGameResponseB\t\n" +
	"\apayload\"=\n" +
	"\x0eStartCountdown\x12+\n" +
	"\x11countdown_seconds\x18\x01 \x01(\x05R\x10countdownSeconds\"\v\n" +
	"\tGameStart\"'\n" +
	"\bJoinGame\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"c\n" +
	"\x10JoinGameResponse\x12)\n" +
	"\aplayers\x18\x01 \x03(\v2\x0f.game.v1.PlayerR\aplayers\x12$\n" +
	"\x05board\x18\x02 \x01(\v2\x0e.game.v1.BoardR\x05board*\x97\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MESSAGE_START_COUNTDOWN\x10\x01\x12\x16\n" +
	"\x12MESSAGE_GAME_START\x10\x02\x12\x15\n" +
	"\x11MESSAGE_JOIN_GAME\x10\x03\x12\x1e\n" +
	"\x1aMESSAGE_JOIN_GAME_RESPONSE\x10\x04B3Z1github.com/tobyrushton/globalfront/pb/messages/v1b\x06proto3"

var (
	file_messages_v1_messages_proto_rawDescOnce sync.Once
	file_messages_v1_messages_proto_rawDescData []byte
)

func file_messages_v1_messages_proto_rawDescGZIP() []byte {
	file_messages_v1_messages_proto_rawDescOnce.Do(func() {
		file_messages_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_v1_messages_proto_rawDesc), len(file_messages_v1_messages_proto_rawDesc)))
	})
	return file_messages_v1_messages_proto_rawDescData
}

var file_messages_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_messages_v1_messages_proto_goTypes = []any{
	(MessageType)(0),         // 0: messages.v1.MessageType
	(*WebsocketMessage)(nil), // 1: messages.v1.WebsocketMessage
	(*StartCountdown)(nil),   // 2: messages.v1.StartCountdown
	(*GameStart)(nil),        // 3: messages.v1.GameStart
	(*JoinGame)(nil),         // 4: messages.v1.JoinGame
	(*JoinGameResponse)(nil), // 5: messages.v1.JoinGameResponse
	(*v1.Player)(nil),        // 6: game.v1.Player
	(*v1.Board)(nil),         // 7: game.v1.Board
}
var file_messages_v1_messages_proto_depIdxs = []int32{
	0, // 0: messages.v1.WebsocketMessage.type:type_name -> messages.v1.MessageType
	2, // 1: messages.v1.WebsocketMessage.start_countdown:type_name -> messages.v1.StartCountdown
	3, // 2: messages.v1.WebsocketMessage.game_start:type_name -> messages.v1.GameStart
	4, // 3: messages.v1.WebsocketMessage.join_game:type_name -> messages.v1.JoinGame
	5, // 4: messages.v1.WebsocketMessage.join_game_response:type_name -> messages.v1.JoinGameResponse
	6, // 5: messages.v1.JoinGameResponse.players:type_name -> game.v1.Player
	7, // 6: messages.v1.JoinGameResponse.board:type_name -> game.v1.Board
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_messages_v1_messages_proto_init() }
func file_messages_v1_messages_proto_init() {
	if File_messages_v1_messages_proto != nil {
		return
	}
	file_messages_v1_messages_proto_msgTypes[0].OneofWrappers = []any{
		(*WebsocketMessage_StartCountdown)(nil),
		(*WebsocketMessage_GameStart)(nil),
		(*WebsocketMessage_JoinGame)(nil),
		(*WebsocketMessage_JoinGameResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_v1_messages_proto_rawDesc), len(file_messages_v1_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_v1_messages_proto_goTypes,
		DependencyIndexes: file_messages_v1_messages_proto_depIdxs,
		EnumInfos:         file_messages_v1_messages_proto_enumTypes,
		MessageInfos:      file_messages_v1_messages_proto_msgTypes,
	}.Build()
	File_messages_v1_messages_proto = out.File
	file_messages_v1_messages_proto_goTypes = nil
	file_messages_v1_messages_proto_depIdxs = nil
}
