// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "messages/v1/messages.proto" (package "messages.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType as MessageType$ } from "@protobuf-ts/runtime";
import { Board } from "../../game/v1/game";
import { Player } from "../../game/v1/game";
/**
 * @generated from protobuf message messages.v1.WebsocketMessage
 */
export interface WebsocketMessage {
    /**
     * @generated from protobuf field: messages.v1.MessageType type = 1
     */
    type: MessageType;
    /**
     * @generated from protobuf oneof: payload
     */
    payload: {
        oneofKind: "startCountdown";
        /**
         * @generated from protobuf field: messages.v1.StartCountdown start_countdown = 2
         */
        startCountdown: StartCountdown;
    } | {
        oneofKind: "gameStart";
        /**
         * @generated from protobuf field: messages.v1.GameStart game_start = 3
         */
        gameStart: GameStart;
    } | {
        oneofKind: "joinGame";
        /**
         * @generated from protobuf field: messages.v1.JoinGame join_game = 4
         */
        joinGame: JoinGame;
    } | {
        oneofKind: "joinGameResponse";
        /**
         * @generated from protobuf field: messages.v1.JoinGameResponse join_game_response = 5
         */
        joinGameResponse: JoinGameResponse;
    } | {
        oneofKind: "spawn";
        /**
         * @generated from protobuf field: messages.v1.Spawn spawn = 6
         */
        spawn: Spawn;
    } | {
        oneofKind: "update";
        /**
         * @generated from protobuf field: messages.v1.Update update = 7
         */
        update: Update;
    } | {
        oneofKind: "attack";
        /**
         * @generated from protobuf field: messages.v1.Attack attack = 8
         */
        attack: Attack;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message messages.v1.StartCountdown
 */
export interface StartCountdown {
    /**
     * @generated from protobuf field: int32 countdown_seconds = 1
     */
    countdownSeconds: number;
}
/**
 * @generated from protobuf message messages.v1.GameStart
 */
export interface GameStart {
}
/**
 * @generated from protobuf message messages.v1.JoinGame
 */
export interface JoinGame {
    /**
     * @generated from protobuf field: string player_id = 1
     */
    playerId: string;
}
/**
 * @generated from protobuf message messages.v1.JoinGameResponse
 */
export interface JoinGameResponse {
    /**
     * @generated from protobuf field: repeated game.v1.Player players = 1
     */
    players: Player[];
    /**
     * @generated from protobuf field: game.v1.Board board = 2
     */
    board?: Board;
}
/**
 * @generated from protobuf message messages.v1.Spawn
 */
export interface Spawn {
    /**
     * @generated from protobuf field: string player_id = 1
     */
    playerId: string;
    /**
     * @generated from protobuf field: int32 tile_id = 2
     */
    tileId: number;
}
/**
 * @generated from protobuf message messages.v1.Update
 */
export interface Update {
    /**
     * @generated from protobuf field: map<int32, string> updated_tiles = 1
     */
    updatedTiles: {
        [key: number]: string;
    };
    /**
     * @generated from protobuf field: map<string, int32> troop_count_changes = 2
     */
    troopCountChanges: {
        [key: string]: number;
    };
}
/**
 * @generated from protobuf message messages.v1.Attack
 */
export interface Attack {
    /**
     * @generated from protobuf field: string player_id = 1
     */
    playerId: string;
    /**
     * @generated from protobuf field: int32 tile_id = 2
     */
    tileId: number;
    /**
     * @generated from protobuf field: int32 troop_count = 3
     */
    troopCount: number;
}
/**
 * @generated from protobuf enum messages.v1.MessageType
 */
export enum MessageType {
    /**
     * @generated from protobuf enum value: MESSAGE_TYPE_UNSPECIFIED = 0;
     */
    MESSAGE_TYPE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: MESSAGE_START_COUNTDOWN = 1;
     */
    MESSAGE_START_COUNTDOWN = 1,
    /**
     * @generated from protobuf enum value: MESSAGE_GAME_START = 2;
     */
    MESSAGE_GAME_START = 2,
    /**
     * @generated from protobuf enum value: MESSAGE_JOIN_GAME = 3;
     */
    MESSAGE_JOIN_GAME = 3,
    /**
     * @generated from protobuf enum value: MESSAGE_JOIN_GAME_RESPONSE = 4;
     */
    MESSAGE_JOIN_GAME_RESPONSE = 4,
    /**
     * @generated from protobuf enum value: MESSAGE_SPAWN = 5;
     */
    MESSAGE_SPAWN = 5,
    /**
     * @generated from protobuf enum value: MESSAGE_UPDATE = 6;
     */
    MESSAGE_UPDATE = 6,
    /**
     * @generated from protobuf enum value: MESSAE_ATTACK = 7;
     */
    MESSAE_ATTACK = 7
}
// @generated message type with reflection information, may provide speed optimized methods
class WebsocketMessage$Type extends MessageType$<WebsocketMessage> {
    constructor() {
        super("messages.v1.WebsocketMessage", [
            { no: 1, name: "type", kind: "enum", T: () => ["messages.v1.MessageType", MessageType] },
            { no: 2, name: "start_countdown", kind: "message", oneof: "payload", T: () => StartCountdown },
            { no: 3, name: "game_start", kind: "message", oneof: "payload", T: () => GameStart },
            { no: 4, name: "join_game", kind: "message", oneof: "payload", T: () => JoinGame },
            { no: 5, name: "join_game_response", kind: "message", oneof: "payload", T: () => JoinGameResponse },
            { no: 6, name: "spawn", kind: "message", oneof: "payload", T: () => Spawn },
            { no: 7, name: "update", kind: "message", oneof: "payload", T: () => Update },
            { no: 8, name: "attack", kind: "message", oneof: "payload", T: () => Attack }
        ]);
    }
    create(value?: PartialMessage<WebsocketMessage>): WebsocketMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = 0;
        message.payload = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<WebsocketMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WebsocketMessage): WebsocketMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* messages.v1.MessageType type */ 1:
                    message.type = reader.int32();
                    break;
                case /* messages.v1.StartCountdown start_countdown */ 2:
                    message.payload = {
                        oneofKind: "startCountdown",
                        startCountdown: StartCountdown.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).startCountdown)
                    };
                    break;
                case /* messages.v1.GameStart game_start */ 3:
                    message.payload = {
                        oneofKind: "gameStart",
                        gameStart: GameStart.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).gameStart)
                    };
                    break;
                case /* messages.v1.JoinGame join_game */ 4:
                    message.payload = {
                        oneofKind: "joinGame",
                        joinGame: JoinGame.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).joinGame)
                    };
                    break;
                case /* messages.v1.JoinGameResponse join_game_response */ 5:
                    message.payload = {
                        oneofKind: "joinGameResponse",
                        joinGameResponse: JoinGameResponse.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).joinGameResponse)
                    };
                    break;
                case /* messages.v1.Spawn spawn */ 6:
                    message.payload = {
                        oneofKind: "spawn",
                        spawn: Spawn.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).spawn)
                    };
                    break;
                case /* messages.v1.Update update */ 7:
                    message.payload = {
                        oneofKind: "update",
                        update: Update.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).update)
                    };
                    break;
                case /* messages.v1.Attack attack */ 8:
                    message.payload = {
                        oneofKind: "attack",
                        attack: Attack.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).attack)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WebsocketMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* messages.v1.MessageType type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        /* messages.v1.StartCountdown start_countdown = 2; */
        if (message.payload.oneofKind === "startCountdown")
            StartCountdown.internalBinaryWrite(message.payload.startCountdown, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* messages.v1.GameStart game_start = 3; */
        if (message.payload.oneofKind === "gameStart")
            GameStart.internalBinaryWrite(message.payload.gameStart, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* messages.v1.JoinGame join_game = 4; */
        if (message.payload.oneofKind === "joinGame")
            JoinGame.internalBinaryWrite(message.payload.joinGame, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* messages.v1.JoinGameResponse join_game_response = 5; */
        if (message.payload.oneofKind === "joinGameResponse")
            JoinGameResponse.internalBinaryWrite(message.payload.joinGameResponse, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* messages.v1.Spawn spawn = 6; */
        if (message.payload.oneofKind === "spawn")
            Spawn.internalBinaryWrite(message.payload.spawn, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* messages.v1.Update update = 7; */
        if (message.payload.oneofKind === "update")
            Update.internalBinaryWrite(message.payload.update, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* messages.v1.Attack attack = 8; */
        if (message.payload.oneofKind === "attack")
            Attack.internalBinaryWrite(message.payload.attack, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message messages.v1.WebsocketMessage
 */
export const WebsocketMessage = new WebsocketMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StartCountdown$Type extends MessageType$<StartCountdown> {
    constructor() {
        super("messages.v1.StartCountdown", [
            { no: 1, name: "countdown_seconds", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<StartCountdown>): StartCountdown {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.countdownSeconds = 0;
        if (value !== undefined)
            reflectionMergePartial<StartCountdown>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StartCountdown): StartCountdown {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 countdown_seconds */ 1:
                    message.countdownSeconds = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StartCountdown, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 countdown_seconds = 1; */
        if (message.countdownSeconds !== 0)
            writer.tag(1, WireType.Varint).int32(message.countdownSeconds);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message messages.v1.StartCountdown
 */
export const StartCountdown = new StartCountdown$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GameStart$Type extends MessageType$<GameStart> {
    constructor() {
        super("messages.v1.GameStart", []);
    }
    create(value?: PartialMessage<GameStart>): GameStart {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GameStart>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GameStart): GameStart {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GameStart, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message messages.v1.GameStart
 */
export const GameStart = new GameStart$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JoinGame$Type extends MessageType$<JoinGame> {
    constructor() {
        super("messages.v1.JoinGame", [
            { no: 1, name: "player_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<JoinGame>): JoinGame {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.playerId = "";
        if (value !== undefined)
            reflectionMergePartial<JoinGame>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JoinGame): JoinGame {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string player_id */ 1:
                    message.playerId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JoinGame, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string player_id = 1; */
        if (message.playerId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.playerId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message messages.v1.JoinGame
 */
export const JoinGame = new JoinGame$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JoinGameResponse$Type extends MessageType$<JoinGameResponse> {
    constructor() {
        super("messages.v1.JoinGameResponse", [
            { no: 1, name: "players", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Player },
            { no: 2, name: "board", kind: "message", T: () => Board }
        ]);
    }
    create(value?: PartialMessage<JoinGameResponse>): JoinGameResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.players = [];
        if (value !== undefined)
            reflectionMergePartial<JoinGameResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JoinGameResponse): JoinGameResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated game.v1.Player players */ 1:
                    message.players.push(Player.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* game.v1.Board board */ 2:
                    message.board = Board.internalBinaryRead(reader, reader.uint32(), options, message.board);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: JoinGameResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated game.v1.Player players = 1; */
        for (let i = 0; i < message.players.length; i++)
            Player.internalBinaryWrite(message.players[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* game.v1.Board board = 2; */
        if (message.board)
            Board.internalBinaryWrite(message.board, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message messages.v1.JoinGameResponse
 */
export const JoinGameResponse = new JoinGameResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Spawn$Type extends MessageType$<Spawn> {
    constructor() {
        super("messages.v1.Spawn", [
            { no: 1, name: "player_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "tile_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Spawn>): Spawn {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.playerId = "";
        message.tileId = 0;
        if (value !== undefined)
            reflectionMergePartial<Spawn>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Spawn): Spawn {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string player_id */ 1:
                    message.playerId = reader.string();
                    break;
                case /* int32 tile_id */ 2:
                    message.tileId = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Spawn, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string player_id = 1; */
        if (message.playerId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.playerId);
        /* int32 tile_id = 2; */
        if (message.tileId !== 0)
            writer.tag(2, WireType.Varint).int32(message.tileId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message messages.v1.Spawn
 */
export const Spawn = new Spawn$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Update$Type extends MessageType$<Update> {
    constructor() {
        super("messages.v1.Update", [
            { no: 1, name: "updated_tiles", kind: "map", K: 5 /*ScalarType.INT32*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } },
            { no: 2, name: "troop_count_changes", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 5 /*ScalarType.INT32*/ } }
        ]);
    }
    create(value?: PartialMessage<Update>): Update {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.updatedTiles = {};
        message.troopCountChanges = {};
        if (value !== undefined)
            reflectionMergePartial<Update>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Update): Update {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* map<int32, string> updated_tiles */ 1:
                    this.binaryReadMap1(message.updatedTiles, reader, options);
                    break;
                case /* map<string, int32> troop_count_changes */ 2:
                    this.binaryReadMap2(message.troopCountChanges, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap1(map: Update["updatedTiles"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof Update["updatedTiles"] | undefined, val: Update["updatedTiles"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.int32();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for messages.v1.Update.updated_tiles");
            }
        }
        map[key ?? 0] = val ?? "";
    }
    private binaryReadMap2(map: Update["troopCountChanges"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof Update["troopCountChanges"] | undefined, val: Update["troopCountChanges"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.int32();
                    break;
                default: throw new globalThis.Error("unknown map entry field for messages.v1.Update.troop_count_changes");
            }
        }
        map[key ?? ""] = val ?? 0;
    }
    internalBinaryWrite(message: Update, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* map<int32, string> updated_tiles = 1; */
        for (let k of globalThis.Object.keys(message.updatedTiles))
            writer.tag(1, WireType.LengthDelimited).fork().tag(1, WireType.Varint).int32(parseInt(k)).tag(2, WireType.LengthDelimited).string(message.updatedTiles[k as any]).join();
        /* map<string, int32> troop_count_changes = 2; */
        for (let k of globalThis.Object.keys(message.troopCountChanges))
            writer.tag(2, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.Varint).int32(message.troopCountChanges[k]).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message messages.v1.Update
 */
export const Update = new Update$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Attack$Type extends MessageType$<Attack> {
    constructor() {
        super("messages.v1.Attack", [
            { no: 1, name: "player_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "tile_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "troop_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Attack>): Attack {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.playerId = "";
        message.tileId = 0;
        message.troopCount = 0;
        if (value !== undefined)
            reflectionMergePartial<Attack>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Attack): Attack {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string player_id */ 1:
                    message.playerId = reader.string();
                    break;
                case /* int32 tile_id */ 2:
                    message.tileId = reader.int32();
                    break;
                case /* int32 troop_count */ 3:
                    message.troopCount = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Attack, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string player_id = 1; */
        if (message.playerId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.playerId);
        /* int32 tile_id = 2; */
        if (message.tileId !== 0)
            writer.tag(2, WireType.Varint).int32(message.tileId);
        /* int32 troop_count = 3; */
        if (message.troopCount !== 0)
            writer.tag(3, WireType.Varint).int32(message.troopCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message messages.v1.Attack
 */
export const Attack = new Attack$Type();
