// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: gamebox/v1/gamebox.proto

package v1

import (
	v1 "github.com/tobyrushton/globalfront/pb/game/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *v1.Game               `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_gamebox_v1_gamebox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamebox_v1_gamebox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_gamebox_v1_gamebox_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRequest) GetGame() *v1.Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_gamebox_v1_gamebox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamebox_v1_gamebox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_gamebox_v1_gamebox_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

var File_gamebox_v1_gamebox_proto protoreflect.FileDescriptor

const file_gamebox_v1_gamebox_proto_rawDesc = "" +
	"\n" +
	"\x18gamebox/v1/gamebox.proto\x12\n" +
	"gamebox.v1\x1a\x12game/v1/game.proto\"6\n" +
	"\x11CreateGameRequest\x12!\n" +
	"\x04game\x18\x01 \x01(\v2\r.game.v1.GameR\x04game\"-\n" +
	"\x12CreateGameResponse\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId2V\n" +
	"\aGamebox\x12K\n" +
	"\n" +
	"CreateGame\x12\x1d.gamebox.v1.CreateGameRequest\x1a\x1e.gamebox.v1.CreateGameResponseB2Z0github.com/tobyrushton/globalfront/pb/gamebox/v1b\x06proto3"

var (
	file_gamebox_v1_gamebox_proto_rawDescOnce sync.Once
	file_gamebox_v1_gamebox_proto_rawDescData []byte
)

func file_gamebox_v1_gamebox_proto_rawDescGZIP() []byte {
	file_gamebox_v1_gamebox_proto_rawDescOnce.Do(func() {
		file_gamebox_v1_gamebox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamebox_v1_gamebox_proto_rawDesc), len(file_gamebox_v1_gamebox_proto_rawDesc)))
	})
	return file_gamebox_v1_gamebox_proto_rawDescData
}

var file_gamebox_v1_gamebox_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gamebox_v1_gamebox_proto_goTypes = []any{
	(*CreateGameRequest)(nil),  // 0: gamebox.v1.CreateGameRequest
	(*CreateGameResponse)(nil), // 1: gamebox.v1.CreateGameResponse
	(*v1.Game)(nil),            // 2: game.v1.Game
}
var file_gamebox_v1_gamebox_proto_depIdxs = []int32{
	2, // 0: gamebox.v1.CreateGameRequest.game:type_name -> game.v1.Game
	0, // 1: gamebox.v1.Gamebox.CreateGame:input_type -> gamebox.v1.CreateGameRequest
	1, // 2: gamebox.v1.Gamebox.CreateGame:output_type -> gamebox.v1.CreateGameResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gamebox_v1_gamebox_proto_init() }
func file_gamebox_v1_gamebox_proto_init() {
	if File_gamebox_v1_gamebox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamebox_v1_gamebox_proto_rawDesc), len(file_gamebox_v1_gamebox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gamebox_v1_gamebox_proto_goTypes,
		DependencyIndexes: file_gamebox_v1_gamebox_proto_depIdxs,
		MessageInfos:      file_gamebox_v1_gamebox_proto_msgTypes,
	}.Build()
	File_gamebox_v1_gamebox_proto = out.File
	file_gamebox_v1_gamebox_proto_goTypes = nil
	file_gamebox_v1_gamebox_proto_depIdxs = nil
}
